## Importing Libraries

In [1]:
import pandas as pd
import numpy as np
import openpyxl
import re

## Parsing monthly_household_est

In [2]:
filepath = 'data/monthly_household_est.xlsx'
skip_rows = 3
n_rows = 72
output = 'data/monthly_household_est.csv'

df = pd.read_excel(filepath, skiprows = skip_rows, nrows=n_rows, header=1)


years = []
months = []
values = []

for i in range(len(df)):
    year = df['Year'][i]
    
    if re.match('....r.', str(year)):
        continue
    for col in df.columns:
        if col == 'Year':
            pass
        elif col=='Jan':
            years.append(year)
            months.append(1)
            values.append(df[col][i])
        elif col=='Feb':
            years.append(year)
            months.append(2)
            values.append(df[col][i])
        elif col=='Mar':
            years.append(year)
            months.append(3)
            values.append(df[col][i])
        elif col=='Apr':
            years.append(year)
            months.append(4)
            values.append(df[col][i])
        elif col=='May':
            years.append(year)
            months.append(5)
            values.append(df[col][i])
        elif col=='Jun':
            years.append(year)
            months.append(6)
            values.append(df[col][i])
        elif col=='Jul':
            years.append(year)
            months.append(7)
            values.append(df[col][i])
        elif col=='Aug':
            years.append(year)
            months.append(8)
            values.append(df[col][i])
        elif col=='Sep':
            years.append(year)
            months.append(9)
            values.append(df[col][i])
        elif col=='Oct':
            years.append(year)
            months.append(10)
            values.append(df[col][i])
        elif col=='Nov':
            years.append(year)
            months.append(11)
            values.append(df[col][i])
        elif col=='Dec':
            years.append(year)
            months.append(12)
            values.append(df[col][i])

df = pd.DataFrame({'Year': years, 'Month': months, 'Val': values})
df.to_csv(output)

## Parsing New_construction

In [3]:
filepath = 'data/New_construction.xlsx'
skip_rows = 7
output = 'data/New_construction.csv'

df = pd.read_excel(filepath, skiprows = skip_rows, header=0)
df = df[['Period', 'Value']]

def month_decode(month):
    if month == 'Jan':
        return 1
    elif month == 'Feb':
        return 2
    elif month == 'Mar':
        return 3
    elif month == 'Apr':
        return 4
    elif month == 'May':
        return 5
    elif month == 'Jun':
        return 6
    elif month == 'Jul':
        return 7
    elif month == 'Aug':
        return 8
    elif month == 'Sep':
        return 9
    elif month == 'Oct':
        return 10
    elif month == 'Nov':
        return 11
    elif month == 'Dec':
        return 12
    

df['Year'] = df['Period'].apply(lambda x: int(x.split('-')[1]))
df['Month'] = df['Period'].apply(lambda x: month_decode(x.split('-')[0]))
df = df[['Year', 'Month', 'Value']]
df.to_csv(output)

## Parsing New_home_sales

In [4]:
filepath = 'data/New_home_sales.xlsx'
skip_rows = 7
output = 'data/New_home_sales.csv'

df = pd.read_excel(filepath, skiprows = skip_rows, header=0)
df = df[['Period', 'Value']]

df['Year'] = df['Period'].apply(lambda x: int(x.split('-')[1]))
df['Month'] = df['Period'].apply(lambda x: month_decode(x.split('-')[0]))
df = df[['Year', 'Month', 'Value']]
df.to_csv(output)

## Parsing quarterly_est_housing_inventory_region

In [5]:
filepath = 'data/quarterly_est_housing_inventory_region.xlsx'
output = 'data/quarterly_est_housing_inventory_region.csv'

wrkbk = openpyxl.load_workbook(filepath) 
sh = wrkbk.active 

quarters = []
years = []
regions = []
vacants = []
occupied = []

for i in range(1, sh.max_row+1):
    if i>852 and i<2693:
        if i%23==3:
            for j in range(1, 6):
                if j==2:
                    cell_obj = sh.cell(row=i, column=j)
                    quarter = cell_obj.value.split(' ')[0]
                    year = cell_obj.value.split(' ')[2]

        elif i%23==5:
            for j in range(1, 6):
                if j>1:
                    cell_obj = sh.cell(row=i, column=j)
                    years.append(year)
                    quarters.append(quarter)
                    regions.append(cell_obj.value)
        elif i%23==9:
            for j in range(1, 6):
                if j>1:
                    cell_obj = sh.cell(row=i, column=j)
                    vacants.append(cell_obj.value)
        elif i%23==21:
            if i>1:
                for j in range(1, 6):
                    if j>1:
                        cell_obj = sh.cell(row=i, column=j)
                        occupied.append(cell_obj.value)
    elif i>=2693 and i<3093:
        if i%25==19:
            for j in range(1, 6):
                if j==2:
                    cell_obj = sh.cell(row=i, column=j)
                    quarter = cell_obj.value.split(' ')[0]
                    year = cell_obj.value.split(' ')[2]

        elif i%25==21:
            for j in range(1, 6):
                if j>1:
                    cell_obj = sh.cell(row=i, column=j)
                    years.append(year)
                    quarters.append(quarter)
                    regions.append(cell_obj.value)
        elif i%25==2:
            for j in range(1, 6):
                if j>1:
                    cell_obj = sh.cell(row=i, column=j)
                    vacants.append(cell_obj.value)
        elif i%25==14:
            if i>1:
                for j in range(1, 6):
                    if j>1:
                        cell_obj = sh.cell(row=i, column=j)
                        occupied.append(cell_obj.value)
df = pd.DataFrame({'Year': years, 'Quarter': quarters, 'Region': regions, 'Vacant': vacants, 'Occupied': occupied})
df = df[df['Year']!='2002r2']

years = []
quarters = []
months = []
regions = []
vacants = []
occupied = []

for index, row in df.iterrows():
    if row['Quarter']=='First':
        for i in range(3):
            years.append(row['Year'])
            months.append(i+1)
            quarters.append(row['Quarter'])
            regions.append(row['Region'])
            vacants.append(row['Vacant'])
            occupied.append(row['Occupied'])
    elif row['Quarter']=='Second':
        for i in range(3):
            years.append(row['Year'])
            months.append(i+4)
            quarters.append(row['Quarter'])
            regions.append(row['Region'])
            vacants.append(row['Vacant'])
            occupied.append(row['Occupied'])
    elif row['Quarter']=='Third':
        for i in range(3):
            years.append(row['Year'])
            months.append(i+7)
            quarters.append(row['Quarter'])
            regions.append(row['Region'])
            vacants.append(row['Vacant'])
            occupied.append(row['Occupied'])
    elif row['Quarter']=='Fourth':
        for i in range(3):
            years.append(row['Year'])
            months.append(i+10)
            quarters.append(row['Quarter'])
            regions.append(row['Region'])
            vacants.append(row['Vacant'])
            occupied.append(row['Occupied'])

df = pd.DataFrame({'Year': years, 'Month': months, 'Region': regions, 'Vacant': vacants, 'Occupied': occupied})
df.to_csv(output)

## Final data integration

In [24]:
# Main data
main_file = 'data/House_sale_main.csv'
monthly_household_est_file = 'data/monthly_household_est.csv'
new_construction_file = 'data/New_construction.csv'
new_home_sales_file = 'data/New_home_sales.csv'
q_est_housing_inv_region_file = 'data/quarterly_est_housing_inventory_region.csv'

main = pd.read_csv(main_file, low_memory=False)
main = main[~main['Date Recorded'].isna()]
monthly_household_est = pd.read_csv(monthly_household_est_file)[['Year', 'Month', 'Val']]
new_construction = pd.read_csv(new_construction_file)[['Year', 'Month', 'Value']]
new_home_sales = pd.read_csv(new_home_sales_file)[['Year', 'Month', 'Value']]
q_est_housing_inv_region = pd.read_csv(q_est_housing_inv_region_file)[['Year', 'Month', 'Region', 'Vacant', 'Occupied']]
q_est_housing_inv_region = q_est_housing_inv_region[q_est_housing_inv_region['Region']=='Northeast'] # Main dataset is onnecticut data

In [25]:
main['Year'] = main['Date Recorded'].apply(lambda x: int(x.split('/')[2]))
main['Month'] = main['Date Recorded'].apply(lambda x: int(x.split('/')[0]))
main = main[['Year', 'Month', 'Town', 'Address', 'Assessed Value', 'Sale Amount', 'Sales Ratio', 'Property Type', 'Residential Type', 'Non Use Code', 'Assessor Remarks', 'OPM remarks', 'Location']]
main

,Year,Month,Town,Address,Assessed Value,Sale Amount,Sales Ratio,Property Type,Residential Type,Non Use Code,Assessor Remarks,OPM remarks,Location
0,2021,4,Ansonia,323 BEAVER ST,133000.0,248400.0,0.535400,Residential,Single Family,NaN,NaN,NaN,POINT (-73.06822 41.35014)
1,2021,5,Ansonia,152 JACKSON ST,110500.0,239900.0,0.460600,Residential,Three Family,NaN,NaN,NaN,NaN
2,2021,9,Ansonia,230 WAKELEE AVE,150500.0,325000.0,0.463000,Commercial,NaN,NaN,NaN,NaN,NaN
3,2020,12,Ansonia,57 PLATT ST,127400.0,202500.0,0.629100,Residential,Two Family,NaN,NaN,NaN,NaN
4,2021,9,Avon,245 NEW ROAD,217640.0,400000.0,0.544100,Residential,Single Family,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
997208,2020,6,New London,4 BISHOP CT,60410.0,53100.0,1.137665,Single Family,Single Family,14 - Foreclosure,NaN,NaN,NaN
997209,2019,11,Waterbury,126 PERKINS AVE,68280.0,76000.0,0.898400,Single Family,Single Family,25 - Other,PRIVATE SALE,NaN,NaN
997210,2020,4,Windsor Locks,19 HATHAWAY ST,121450.0,210000.0,0.578300,Single Family,Single Family,NaN,NaN,NaN,NaN
997211,2020,6,Middletown,8 BYSTREK DR,203360.0,280000.0,0.726300,Single Family,Single Family,NaN,NaN,NaN,NaN
997212,2019,12,Milford,250 RESEARCH DR,4035970.0,7450000.0,0.541700,NaN,NaN,NaN,NaN,NaN,NaN

In [40]:
merged = main.merge(monthly_household_est, how='left', on=['Year', 'Month']).rename({'Val': 'Val_monthly_household_est'}, axis='columns')
merged = merged.merge(new_construction, how='left', on=['Year', 'Month']).rename({'Value': 'Val_new_construction'}, axis='columns')
merged = merged.merge(new_home_sales, how='left', on=['Year', 'Month']).rename({'Value': 'Val_new_home_sales'}, axis='columns')
merged =merged.merge(q_est_housing_inv_region[['Year', 'Month', 'Vacant', 'Occupied']], how='left', on=['Year', 'Month'])

In [41]:
output = 'data/merged.csv'
merged.to_csv(output)